language: node_js
node_js:
  - "0.12"
before_install:
  - chmod 755 ./update-gh-pages.sh
before_script:
  - npm install -g gulp
  - npm install -g bower
  - bower install
script: gulp build
after_success: ./update-gh-pages.sh
